// Hyprland "decorations" domain. Draft state is JSON-backed (mirrors
// Settings.qml's pattern) and is the single source of truth quickshell
// reads/writes. hypr/generated/decorations.lua is a pure, one-way
// compilation target - regenerated from this JSON on every save(), never
// parsed back. Live preview goes through `hyprctl keyword`, debounced and
// batched (see save()/applyLive()) so dragging a slider doesn't spam the
// compositor with one IPC call per pixel.

pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs

Singleton {
  id: root

  property alias gapsIn: jsonAdapter.gapsIn
  property alias gapsOut: jsonAdapter.gapsOut
  property alias borderSize: jsonAdapter.borderSize
  property alias resizeOnBorder: jsonAdapter.resizeOnBorder
  property alias allowTearing: jsonAdapter.allowTearing
  property alias layout: jsonAdapter.layout
  property alias rounding: jsonAdapter.rounding
  property alias activeOpacity: jsonAdapter.activeOpacity
  property alias inactiveOpacity: jsonAdapter.inactiveOpacity
  property alias blurEnabled: jsonAdapter.blurEnabled
  property alias shadowEnabled: jsonAdapter.shadowEnabled
  property alias animationsEnabled: jsonAdapter.animationsEnabled

  function scheduleLiveApply(): void {
    liveApplyDebounce.restart();
  }

  Timer {
    id: liveApplyDebounce
    interval: 150
    onTriggered: root.applyLive()
  }

  // hyprctl keyword only works against the legacy (non-Lua) config parser -
  // "keyword can't work with non-legacy parsers. Use eval." on this setup.
  // `eval` takes a raw Lua string instead, so live preview reuses the exact
  // same hl.config({...}) text save() writes to the generated file.
  function applyLive(): void {
    Quickshell.execDetached(["hyprctl", "eval", configLua()]);
  }

  onGapsInChanged: scheduleLiveApply()
  onGapsOutChanged: scheduleLiveApply()
  onBorderSizeChanged: scheduleLiveApply()
  onResizeOnBorderChanged: scheduleLiveApply()
  onAllowTearingChanged: scheduleLiveApply()
  onLayoutChanged: scheduleLiveApply()
  onRoundingChanged: scheduleLiveApply()
  onActiveOpacityChanged: scheduleLiveApply()
  onInactiveOpacityChanged: scheduleLiveApply()
  onBlurEnabledChanged: scheduleLiveApply()
  onShadowEnabledChanged: scheduleLiveApply()
  onAnimationsEnabledChanged: scheduleLiveApply()

  function luaValue(v): string {
    if (typeof v === "string") return '"' + v + '"';
    if (typeof v === "boolean") return v ? "true" : "false";
    return String(v);
  }

  function configLua(): string {
    return "hl.config({\n" +
      "    general = {\n" +
      "        gaps_in = " + luaValue(root.gapsIn) + ",\n" +
      "        gaps_out = " + luaValue(root.gapsOut) + ",\n" +
      "        border_size = " + luaValue(root.borderSize) + ",\n" +
      "        resize_on_border = " + luaValue(root.resizeOnBorder) + ",\n" +
      "        allow_tearing = " + luaValue(root.allowTearing) + ",\n" +
      "        layout = " + luaValue(root.layout) + ",\n" +
      "    },\n" +
      "    decoration = {\n" +
      "        rounding = " + luaValue(root.rounding) + ",\n" +
      "        active_opacity = " + luaValue(root.activeOpacity) + ",\n" +
      "        inactive_opacity = " + luaValue(root.inactiveOpacity) + ",\n" +
      "        blur = {\n" +
      "            enabled = " + luaValue(root.blurEnabled) + ",\n" +
      "        },\n" +
      "        shadow = {\n" +
      "            enabled = " + luaValue(root.shadowEnabled) + ",\n" +
      "        },\n" +
      "    },\n" +
      "    animations = {\n" +
      "        enabled = " + luaValue(root.animationsEnabled) + ",\n" +
      "    },\n" +
      "})";
  }

  function save(): void {
    settingsFile.writeAdapter();
    generatedFile.setText(
      "-- AUTO-GENERATED by the Peridot settings app - do not edit by hand,\n" +
      "-- changes here will be overwritten. Edit via the settings app instead.\n\n" +
      configLua() + "\n"
    );
  }

  function revert(): void {
    settingsFile.reload();
    Quickshell.execDetached(["hyprctl", "reload"]);
  }

  FileView {
    id: settingsFile
    path: Quickshell.env("HOME") + "/.config/peridot/settings/hyprland-decorations.json"
    watchChanges: true
    onFileChanged: reload()

    JsonAdapter {
      id: jsonAdapter

      property int gapsIn: 2
      property int gapsOut: 6
      property int borderSize: 1
      property bool resizeOnBorder: true
      property bool allowTearing: false
      property string layout: "dwindle"

      property int rounding: 12
      property real activeOpacity: 1.0
      property real inactiveOpacity: 0.92
      property bool blurEnabled: true
      property bool shadowEnabled: true

      property bool animationsEnabled: true
    }
  }

  FileView {
    id: generatedFile
    path: Quickshell.env("HOME") + "/.config/hypr/generated/decorations.lua"
  }
}
