// Hyprland "input" domain. Same shape as HyprlandDecorations.qml - see that
// file for the reasoning behind the JSON-source-of-truth / generated-Lua /
// debounced-batched-hyprctl design.

pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs
import qs.common

Singleton {
  id: root

  property alias kbLayout: jsonAdapter.kbLayout
  property alias followMouse: jsonAdapter.followMouse
  property alias sensitivity: jsonAdapter.sensitivity
  property alias naturalScroll: jsonAdapter.naturalScroll

  function scheduleLiveApply(): void {
    liveApplyDebounce.restart();
  }

  Timer {
    id: liveApplyDebounce
    interval: 150
    onTriggered: root.applyLive()
  }

  // hyprctl keyword only works against the legacy (non-Lua) config parser -
  // "keyword can't work with non-legacy parsers. Use eval." on this setup.
  // `eval` takes a raw Lua string instead, so live preview reuses the exact
  // same hl.config({...}) text a save writes to the generated file.
  function applyLive(): void {
    Quickshell.execDetached(["hyprctl", "eval", configLua(root)]);
  }

  onKbLayoutChanged: scheduleLiveApply()
  onFollowMouseChanged: scheduleLiveApply()
  onSensitivityChanged: scheduleLiveApply()
  onNaturalScrollChanged: scheduleLiveApply()

  function luaValue(v): string {
    if (typeof v === "string") return '"' + v + '"';
    if (typeof v === "boolean") return v ? "true" : "false";
    return String(v);
  }

  // `v` is root (live values) for previews, store.savedValues for the file.
  function configLua(v): string {
    return "hl.config({\n" +
      "    input = {\n" +
      "        kb_layout = " + luaValue(v.kbLayout) + ",\n" +
      "        follow_mouse = " + luaValue(v.followMouse) + ",\n" +
      "        sensitivity = " + luaValue(v.sensitivity) + ",\n" +
      "        touchpad = {\n" +
      "            natural_scroll = " + luaValue(v.naturalScroll) + ",\n" +
      "        },\n" +
      "    },\n" +
      "})";
  }

  readonly property SettingsStore store: SettingsStore {
    path: Quickshell.env("HOME") + "/.config/peridot/settings/hyprland-input.json"

    onSaved: generatedFile.setText(
      "-- AUTO-GENERATED by the Peridot settings app - do not edit by hand,\n" +
      "-- changes here will be overwritten. Edit via the settings app instead.\n\n" +
      root.configLua(root.store.savedValues) + "\n"
    )

    JsonAdapter {
      id: jsonAdapter

      property string kbLayout: "se"
      property int followMouse: 1
      property real sensitivity: -0.3
      property bool naturalScroll: true
    }
  }

  FileView {
    id: generatedFile
    path: Quickshell.env("HOME") + "/.config/hypr/generated/input.lua"
  }
}
