#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &

force_default_wallpaper = 0    # Set to 0 or -1 to disable the anime mascot
disable_hyprland_logo = true
exec-once = qs & waypaper --restore
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Preload Firefox
exec-once = [workspace 99 silent] firefox

exec-once = hyprctl setcursor Bibata-Modern-Ice 22