cursor            #edb4eb
cursor_text_color #4a204c

foreground            #ebdfe6
background            #120d11
selection_foreground  #3c2b3b
selection_background  #d8bfd4
url_color             #d8bfd4

#: black 000000 767676
color0  #171216
color8  #393338
#: red cc0403 f2201f
color1  #853c42
color9  #cc8e93
#: green 19cb00 23fd00
color2  #d8bfd4
color10 #f5dbf0
#: yellow cecb00 fffd00
color3  #f6b8ab
color11 #ffdad3
#: blue 0d73cc 1a8fff
color4  #633664
color12 #edb4eb
#: magenta cb1ed1 fd28ff
color5  #534152
color13 #d8bfd4
#: cyan 0dcdcd 14ffff
color6  #673b32
color14 #f6b8ab
#: white dddddd ffffff
color7  #d0c3cc
color15 #ebdfe6

mark1_foreground #320936
mark1_background #ffd6fb
mark2_foreground #261626
mark2_background #f5dbf0
mark3_foreground #33110b
mark3_background #ffdad3

active_tab_foreground #4a204c
active_tab_background #edb4eb
inactive_tab_foreground #ffd6fb
inactive_tab_background #633664

active_border_color #edb4eb
inactive_border_color #4a204c
# bell_border_color #ff5a00
