# Generated by matugen — keep autosuggestion text on the "outline" role,
# which Material You always keeps mid-tone so it stays legible against
# a dark terminal background instead of blending into it.
set -g fish_color_autosuggestion '{{colors.outline.dark.hex}}'
